- log_source_type: "Apache Access Log"
  required_fields:
    - timestamp
    - request_method
    - request_url
    - response_code
  parsing_patterns:
    - '(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})'
    - '([A-Z]+)'
    - '(/[\w/]+)'
    - '(\d{3})'

- log_source_type: "Nginx Error Log"
  required_fields:
    - timestamp
    - level
    - message
  parsing_patterns:
    - '(\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2})'
    - '([A-Z]+)'
    - '(.+)'

- log_source_type: "Custom Log"
  required_fields:
    - timestamp
    - log_level
    - log_message
  parsing_patterns:
    - '(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})'
    - '([A-Z]+)'
    - '(.+)'

- log_source_type: "ameer"
  parsing_patterns:
  - "(\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2})\r"
  - "([A-Z]+)\r"
  - (/[\w/]+)
  required_fields:
  - "time\r"
  - "url\r"
  - ip
